### ISSUE TITLE
Receiving srv records with binary instead of tuple

### ISSUE THREAD

**Issue by lawik** [nerves-networking/mdns_lite#59]
**Describe the bug**
A cache query in my [keylight](https://github.com/lawik/keylight) started returning a binary instead of the tuple I match for in srv_to_host.

I ran into it during a livestream so I have a video: https://youtu.be/1fO_ow8cA_Y (one example visible at 23.36 shows both record and binary)

**To Reproduce**

See video, I don't know what differs between this and the times I've used mdns_lite to set up erlang distribution. Maybe a pi0 system update?

I'll try to look closer at it and see if I can give something more useful.

**Expected behavior**
Missing for now.

**VintageNet Info**

Missing for now.

**Environment**

* Nerves environment: (`mix nerves.env --info`)
* Additional information about your host, target hardware or environment that might help

**Comment by fhunleth** [comment]
@lawik The fix to erlang/otp#5327 has been merged to `maint`. Since it's going to be a while (a year or more?) until everyone has the fix, I decided to vendor the fix code with the fix in `mdns_lite`. I used your Elgato Key Light packet in the unit tests, so I'm pretty sure this will fix your issue when it's merged.

**Comment by lawik** [comment]
Thanks, very cool :)
